version: "3"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    desc: Run main.go with flags
    cmds:
      - go run ./...

  lint:
    desc: Lint all go files in DIR.
    cmds:
      - golangci-lint run --timeout 10m0s ./...

  test:
    desc: Test all go files in DIR.
    cmds:
      - go test ./...

  cover:
    desc: Show test coverage
    cmds:
      - go test -cover ./...
  
  coverHTML:
    desc: Show test coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - rm coverage.out
      - brave-browser coverage.html

